daemonURL: "http://sanfran.equilibria.network:9231"
APIPort: ":4000"
RateLimitTime: 60 #Minutes
RateLimitRequests: 2000 #Num Reqs in RateLimitTime
databaseName: xeq_api
databaseHost: localhost
databaseUsername: admin
databasePassword: admin